
package com.gps19.core.engine

/**
 * EngineConstants: Logic-specific thresholds for the tracking engine.
 * v9.3.17:
 * - R403: Startup ANR Remediation. centralizing dynamic heartbeat logic.
 *   Introduced STARTUP_TICK_INTERVAL_MS (2s) and DEFAULT_TICK_INTERVAL_MS (2s).
 *   Added getHeartbeatInterval helper for cross-component synchronization.
 */

const val EARTH_RADIUS_METERS = 6371000.0
const val LAT_DEG_TO_METERS = 111194.92664455874
const val GRAVITY_EARTH = 9.80665

// Global App Defaults (Inherited by Engine)
const val DEFAULT_LAT = 32.7940
const val DEFAULT_LNG = 34.9896

// Physics & Motion Limits
const val MAX_PHYSICAL_SPEED_MPS = 33.33 // 120 km/h
const val OUTLIER_SPEED_CAP_MPS = 83.33 // 300 km/h
const val JUMP_POINT_DISTANCE_THRESHOLD = 100.0 
const val OUTLIER_DISTANCE_THRESHOLD = 2000.0 
const val ABSOLUTE_DISTANCE_CAP_METERS = 50000.0
const val MAX_TRACTOR_ACCEL = 2.0 
const val PARKING_ACCEL_LIMIT = 1.0
const val ALTITUDE_VELOCITY_CAP = 10.0 
const val VERTICAL_VELOCITY_MAX_MPS = 5.0
const val PROMOTION_ANGLE_TOLERANCE = 30.0 
const val PATH_EFFICIENCY_THRESHOLD = 0.1 
const val COMPASS_STABILITY_THRESHOLD = 20.0 
const val WILD_JUMP_THRESHOLD_METERS = 500000.0
const val MONOTONIC_JITTER_TOLERANCE_MS = 2000L

// Jump Engine Weights & Gates
const val JUMP_WEIGHT_SENSOR_MISMATCH = 60
const val JUMP_WEIGHT_ACCEL_CHECK = 40
const val JUMP_WEIGHT_ALTITUDE_DELTA = 30
const val JUMP_WEIGHT_TRADITIONAL_SPEED = 50
const val JUMP_WEIGHT_ACCURACY_LOW = 30
const val JUMP_WEIGHT_ACCURACY_HIGH = 20

const val JUMP_GATE_SENSOR_MISMATCH_MPS = 2.0
const val JUMP_GATE_SENSOR_MISMATCH_A15_MPS = 5.0 // Issue #036: Hardened for A15 jitter
const val JUMP_GATE_SPEED_ACCURACY_LOW_MPS = 22.2
const val JUMP_GATE_SPEED_ACCURACY_HIGH_MPS = 8.3
const val JUMP_GATE_ACCURACY_LOW_THRESHOLD = 40.0
const val JUMP_GATE_ACCURACY_HIGH_THRESHOLD = 150.0
const val JUMP_GATE_VISUAL_JITTER_METERS = 10.0
const val JUMP_GATE_VISUAL_JITTER_A15_METERS = 25.0 // Issue #036: Hardened for A15 jitter

// Adaptive Jump Confidence (v8.9.18 - Issue #332 / R332)
const val ADAPTIVE_JUMP_SNR_THRESHOLD = 35.0
const val ADAPTIVE_JUMP_HOLD_MULTIPLIER = 2.0

// Hindsight Correction (v8.9.18 - Issue #334 / R334)
const val HINDSIGHT_BUFFER_SIZE = 10 // Issue #461: Forensic Parity
const val HINDSIGHT_MAX_AGE_MS = 30000L

// Bayesian Uncertainty Growth (R460 / Issue #460)
const val PENDING_UNCERTAINTY_GROWTH_RATE_MPS = 15.0 // 54 km/h conservative drift
const val PENDING_UNCERTAINTY_DRIFT_STATIONARY_MPS = 1.5 // Minimal drift when stationary
const val PENDING_UNCERTAINTY_SPEED_CAP_MPS = 33.3 // 120 km/h cap

// ImmFilter Parameters
const val IMM_STATIONARY_PROBABILITY = 0.8
const val IMM_KINEMATIC_PROBABILITY = 0.2
const val IMM_MIN_MEASUREMENT_NOISE_METERS = 5.0
const val IMM_STATIONARY_Q_POS = 0.01
const val IMM_STATIONARY_Q_VEL = 0.001
const val IMM_KINEMATIC_Q_POS = 0.5
const val IMM_KINEMATIC_Q_VEL = 0.2
const val IMM_STALL_RECOVERY_DT_SEC = 60.0

// Behavioral Sentinel Checks
const val JUMP_CHECK_MIN_DIST = 5.0
const val ACCEL_CHECK_MIN_DIST = 10.0
const val EFFICIENCY_MIN_SEGMENT_DIST = 10.0
const val EFFICIENCY_MIN_TOTAL_DIST = 50.0
const val SCATTER_MIN_SPEED_MPS = 0.5
const val SCATTER_ANGLE_THRESHOLD = 120.0

// Acoustic Monitoring (R810-L)
const val BREACH_THRESHOLD_DB_JUMP = 40.0 
const val BREACH_THRESHOLD_DB_JUMP_A15 = 55.0 
const val ACOUSTIC_THRESHOLD_DB_JUMP = 40.0 
const val ACOUSTIC_THRESHOLD_DB_JUMP_A15 = 55.0 
const val ACOUSTIC_SUSPICIOUS_THRESHOLD_DB_JUMP = 20.0
const val ACOUSTIC_MIN_THRESHOLD_DB = 50.0
const val ACOUSTIC_FLOOR_MIN_DB = 50.0 
const val ACOUSTIC_FLOOR_CONTRACTION_EMA = 0.995
const val ACOUSTIC_LOCKOUT_MS = 1000L
const val ACOUSTIC_RECOVERY_DELAY_MS = 30000L
const val ACOUSTIC_SAMPLE_RATE = 8000
const val ACOUSTIC_INIT_RETRY_COUNT = 3
const val ACOUSTIC_INIT_RETRY_DELAY_MS = 200L
const val ACOUSTIC_GENERIC_RECOVERY_DELAY_MS = 2000L

// Physical Security Sentinel (R810-M)
const val LIGHT_THRESHOLD_LUX_JUMP = 150.0
const val TILT_THRESHOLD_DEGREES = 15.0
const val BARO_LIFT_THRESHOLD_METERS = 0.8
const val VIBRATION_SUSPICIOUS_THRESHOLD_G = 0.25
const val VIBRATION_SHOCK_THRESHOLD_G = 0.8 
const val VIBRATION_STATIONARY_THRESHOLD = 0.12 
const val STATIONARY_FLOOR_MULT = 1.5
const val VIBRATION_SHOCK_MULTIPLIER = 7.0
const val VIBRATION_SUSPICIOUS_MULTIPLIER = 2.5
const val INITIAL_VIBRATION_FLOOR = 0.05
const val VIBRATION_WINDOW_SIZE = 5 
const val PASSIVE_ZEROING_STATIONARY_MS = 300000L
const val ROTATION_INIT_STATIONARY_MS = 3000L
const val BARO_ZEROING_INTERVAL_MS = 300000L 
const val SPIKE_DEBOUNCE_MS = 5000L

// Chair Sit Detection (R832 - Issue #459)
const val CHAIR_SIT_TILT_THRESHOLD = 7.0 
const val CHAIR_SIT_VIBRATION_THRESHOLD = 0.35 
const val CHAIR_SIT_BARO_THRESHOLD = 0.08 
const val CHAIR_PLUNGE_VELOCITY_THRESHOLD = 0.18 
const val CHAIR_PLUNGE_DISTANCE_THRESHOLD = 0.05 
const val CHAIR_PLUNGE_WINDOW_MS = 800L
const val CHAIR_PLUNGE_PHASE_TIMEOUT_MS = 1500L
const val CHAIR_SIT_COOLDOWN_MS = 5000L
const val SIT_TRANSMISSION_LATCH_MS = 10000L
const val SIT_DUPLICATE_GUARD_MS = 15000L

// Filtering Thresholds (R810-P Zero-Lag)
const val SUSPICIOUS_Q_SCALE = 1000.0
const val TRAJECTORY_PROMOTION_WINDOW_MS = 30000L 
const val HIGH_ACCURACY_THRESHOLD_METERS = 35.0

/**
 * Multiplier applied to [HIGH_ACCURACY_THRESHOLD_METERS] to determine the floor 
 * for trajectory-based outlier rejection.
 * Used in [LocationProcessor] to reject low-accuracy points following high-accuracy fixes.
 */
const val TRAJECTORY_REJECTION_ACCURACY_MULT = 3.0

// Issue #024: Increased to 120s to ensure buckets (30s) exceed stationary polling (20s)
const val ACCURACY_WINDOW_BUCKET_MS = 120000L
const val ACCURACY_WINDOW_MAX_SIZE = 4
const val GEOFENCE_ACCURACY_HYSTERESIS_MULT = 1.10
const val GEOFENCE_ACCURACY_EXPANSION_MULT = 1.0
const val GEOFENCE_BUFFER_MULT = 6.0
const val GEOFENCE_HYSTERESIS_METERS = 5.0
const val GEOFENCE_PREDICTIVE_LOOKAHEAD_S = 2.0
const val GEOFENCE_PREDICTIVE_MIN_SPEED_MPS = 1.0

// EMA Factors (Issue #263: Corrected Inversion)
const val LUX_EMA_SLOW = 0.01
const val LUX_EMA_FAST = 0.1
const val LUX_EMA_UP_SLOW = 0.001
const val LUX_EMA_UP_FAST = 0.01
const val LUX_EMA_UP_FAST_A15 = 0.05 // Optimized for A15 LED flutter
const val LUX_EMA_DOWN_SLOW = 0.001
const val LUX_EMA_DOWN_FAST = 0.02
const val ACOUSTIC_EMA_DOWN_SLOW = 0.001
const val ACOUSTIC_EMA_DOWN_FAST = 0.02
const val ACOUSTIC_EMA_UP_SLOW = 0.0001
const val ACOUSTIC_EMA_UP_FAST = 0.01
const val VIBRATION_EMA_DOWN_SLOW = 0.01
const val VIBRATION_EMA_DOWN_FAST = 0.1
const val VIBRATION_EMA_UP_SLOW = 0.001
const val VIBRATION_EMA_UP_FAST = 0.01
const val BARO_EMA_SLOW = 0.001 

// GtoEngine Optimization Constants (Issue #264)
const val GTO_TOW_SPEED_THRESHOLD = 10.0
const val GTO_KINEMATIC_SPEED_DELTA = 10.0
const val GTO_WORK_SPEED_THRESHOLD = 5.0

// Engine Execution Parameters
const val BOOTSTRAP_PHASE_MS = 60000L
const val DISCOVERY_PHASE_MS = 60000L
const val JUMP_HOLD_DURATION_MS = 180000L
const val MOVING_HOLD_DURATION_MS = 60000L
const val STATIONARY_GPS_POLLING_MS = 20000L
const val MOVING_GPS_POLLING_MS = 200L 
const val SUSPICIOUS_GPS_POLLING_MS = 1000L
const val HIGH_FREQUENCY_GPS_POLLING_MS = 100L
const val A15_STABLE_GPS_POLLING_MS = 1000L
const val COOLING_GPS_POLLING_MS = 30000L
const val SCREEN_OFF_GPS_POLLING_MS = 5000L // R994: Reduced frequency when screen is off
const val VIEWER_GPS_POLLING_MS = 1000L 
const val GPS_GAP_THRESHOLD_MS = 60000L
const val GPS_STALL_THRESHOLD_MS = 60000L
const val JAMMER_DETECTION_THRESHOLD_MS = 180000L
const val TICK_INTERVAL_MS = 1000L
const val DEFAULT_TICK_INTERVAL_MS = 2000L 
const val STARTUP_TICK_INTERVAL_MS = 2000L // R403: Relaxed heartbeat for startup performance
const val TICK_INTERVAL_SLOW_MS = 5000L
const val UI_PULSE_TIMEOUT_MS = 45000L // Issue #025: Relaxed to 45s to harden FGS transitions
const val FGS_STICKY_DELAY_MS = 45000L
const val WATCH_TIMEOUT_MS = 15000L // Issue #427/428: Relaxed to 15s to handle network jitter
const val CLOCK_REGRESSION_GATE_MS = 100L
const val SENSOR_WARMING_MS = 5000L
const val SUSPICIOUS_STATE_COOLDOWN_MS = 60000L
const val MUZZLE_WINDOW_DURATION_MS = 2000L
const val MUZZLE_HYSTERESIS_MS = 200L
const val MUZZLE_HYSTERESIS_A15_MS = 500L
const val ADAPTATION_SETTLING_MS = 5000L // Issue #038: Settle duration after polling change
const val GPS_REVIVAL_RETRY_INTERVAL_MS = 120000L
const val MAX_REVIVAL_ATTEMPTS = 3
const val XIAOMI_BOOT_GRACE_MS = 30000L
const val LANDING_PAGE_PAUSE_MS = 2000L

/**
 * R403: Returns the active system heartbeat interval based on initialization state.
 */
fun getActiveHeartbeatInterval(elapsedMs: Long, isHighResDevice: Boolean = true): Long {
    if (elapsedMs < BOOTSTRAP_PHASE_MS) return STARTUP_TICK_INTERVAL_MS
    return if (isHighResDevice) TICK_INTERVAL_MS else DEFAULT_TICK_INTERVAL_MS
}

// Xiaomi Heuristic Recovery (Issue #190)
const val XIAOMI_SUPPRESSION_THRESHOLD_MS = 15000L
const val XIAOMI_RECOVERY_COOLDOWN_MS = 60000L

const val ACTIVE_MOVE_THRESHOLD = 2.0
const val GPS_SAVE_INTERVAL_MS = 20000L // Issue #436: Aligned with STATIONARY_GPS_POLLING_MS

// Stationary Anchor Monitor (Issue #062)
const val PARKING_ANCHOR_MIN_DIST = 20.0
const val PARKING_ANCHOR_FACTOR = 0.8
const val ANCHOR_ESCAPE_SCORE_THRESHOLD = 100.0
const val ANCHOR_TREND_WINDOW_SIZE = 3
const val ANCHOR_TRANSITION_ZONE_START = 0.7 // Start accumulating score at 70% of threshold
const val ANCHOR_VELOCITY_WEIGHT_MPS = 15.0 // Score points per m/s of estimated speed

const val DEDUPLICATION_SPATIAL_GATE_FACTOR = 0.5 // Issue #450: Authoritative multiplier

// Behavioral State Thresholds (Issue #302)
const val SUSTAINED_SPEED_THRESHOLD = 2 
const val SUSTAINED_SPEED_STATIONARY_THRESHOLD = 4
const val STATE_CONFIDENCE_BUFFER_MS = 2000L
const val PARKING_CONFIDENCE_BUFFER_MS = 5000L
const val HIGH_SPEED_PROMOTION_THRESHOLD = 5.0

// Throttling Limits
const val THROTTLE_LUX_LIMIT = 50.0
const val THROTTLE_TILT_LIMIT = 5.0
const val THROTTLE_ACOUSTIC_LIMIT = 15.0
const val THROTTLE_COMPASS_LIMIT = 5.0
const val THROTTLE_BARO_LIMIT = 0.5

// System Thresholds (Core Logic)
const val TRACKER_SIGNAL_LOSS_THRESHOLD_MS = 180000L
const val VIEWER_SIGNAL_LOSS_THRESHOLD_MS = 30000L
const val INTERNET_LOSS_THRESHOLD_MS = 60000L 
const val DISTANCE_ALARM_SAMPLES_REQUIRED = 6
const val DEFAULT_ACCURACY_FALLBACK = 15.0
const val RETURN_TO_SAFE_RANGE_ACCURACY_LIMIT = 20.0

// Battery thresholds (R716e)
const val BATTERY_ALARM_THRESHOLD = 20
const val CRITICAL_BATTERY_THRESHOLD = 20
const val MAX_SAFE_TEMPERATURE_CELSIUS = 46.0
const val MAX_SAFE_TEMPERATURE_RECOVERY = 44.0
const val BATTERY_STEEP_DISCHARGE_THRESHOLD = 5
const val BATTERY_STEEP_DISCHARGE_WINDOW_MS = 600000L

// Storage thresholds
const val SYSTEM_STORAGE_CRITICAL_THRESHOLD_MB = 10L
const val SYSTEM_STORAGE_LOW_THRESHOLD_MB = 50L

// GPS Polling & Filtering (v8.7.5 Centralization)
const val GPS_SEQUENCE_TOLERANCE_MS = 60000L
const val GPS_MIN_UPDATE_DISTANCE_METERS = 2.0

// Analytical Index Thresholds
const val GPS_INDEX_AGE_EXCELLENT_SEC = 5.0
const val GPS_INDEX_AGE_SCALING = 2.0
const val GPS_INDEX_ACCURACY_EXCELLENT_METERS = 8.0
const val GPS_INDEX_SATS_TARGET = 12

// Forensic Ribbon Scaling
const val RIBBON_NOISE_SCALE_DB = 40.0
const val RIBBON_LUX_LOG_SCALE = 5.0
const val RIBBON_VIBRATION_SCALE_G = 2.0
const val RIBBON_LIFT_SCALE_METERS = 5.0
const val RIBBON_SNR_SCALE_DB = 45.0
const val RIBBON_CURRENT_SCALE_MA = 1000.0
const val RIBBON_SIT_TILT_SCALE_DEG = 15.0
const val RIBBON_SIT_BARO_SCALE_METERS = 0.5

const val SENSOR_SAMPLE_BUFFER_MAX_AGE_MS = 300000L

// Network Communication (v8.8.21)
// Issue #315: Maximum healthy RTT for sync loop scaling.
const val MAX_ALLOWED_RTT_MS = 5000
const val COMM_RTT_FLOOR_MS = 150
const val COMM_RTT_SCALING_FACTOR = 2000.0
const val NETWORK_TIMEOUT_MS = 10000
const val NET_REJOIN_THRESHOLD_MS = 15000L
const val NET_HEAL_THRESHOLD_MS = 45000L
// Issue #315: Baseline sync interval.
const val PING_INTERVAL_MS = 10000L
const val SOCKET_TIMEOUT_MS = 60000
const val RTT_WINDOW_SIZE = 5

// Trajectory & Persistence (v8.8.35)
const val HOME_POINT_REFRESH_INTERVAL_MS = 30000L

// Logging & UI (v8.9.2)
const val LOG_MUZZLE_STARTUP_MS = 10000L
const val GPS_TRANSITION_LOG_MUZZLE_MS = 30000L
const val MAX_HISTORY_POINTS_PER_RIBBONS = 240
const val GPS_STABILITY_AUDIT_INTERVAL_MS = 10000L
const val GPS_STABILITY_GAP_THRESHOLD_MS = 200L
const val GPS_STABILITY_RELIABILITY_THRESHOLD = 98.0

// R338: Unified UI Staleness Threshold (15s) - Relaxed to accommodate jitter
// Issue #002: Increased to 35s to cover STATIONARY_GPS_POLLING_MS (20s)
const val TELEMETRY_UI_STALE_THRESHOLD_MS = 35000L
const val GPS_UI_FAIL_THRESHOLD_MS = 35000L

// R993: Notification Throttling
const val NOTIFICATION_THROTTLE_MS = 10000L

// Alert Internal IDs (Aligned with SoT)
const val ALERT_ID_LOCAL_INTERNET = "LOCAL_INTERNET"
const val ALERT_ID_RELAY_OFFLINE = "RELAY_OFFLINE"
const val ALERT_ID_TRACKER_OFFLINE = "TRACKER_OFFLINE"
const val ALERT_ID_SIGNAL_LOSS = "SIGNAL_LOSS"
const val ALERT_ID_JUMP_ALERT = "JUMP_ALERT"
const val ALERT_ID_VISUAL_JUMP = "VISUAL_JUMP"
const val ALERT_ID_TRACKER_GEOFENCE = "GEOFENCE_VIOLATION"
const val ALERT_ID_GPS_STALL = "GPS_STALL"
const val ALERT_ID_TRACKER_GAP = "GPS_GAP"
const val ALERT_ID_TRACKER_POWER = "POWER_TAMPER"
const val ALERT_ID_TRACKER_BATTERY = "LOW_BATTERY"
const val ALERT_ID_TRACKER_TEMP = "TRACKER_TEMP"
const val ALERT_ID_TRACKER_TAMPER = "TRACKER_TAMPER"
const val ALERT_ID_TRACKER_TILT = "TILT_ALERT"
const val ALERT_ID_TRACKER_ACOUSTIC = "ACOUSTIC_ALERT"
const val ALERT_ID_TRACKER_LIFT = "LIFT_ALERT"
const val ALERT_ID_TRACKER_CHAIR = "CHAIR_OCCUPIED"
const val ALERT_ID_SYSTEM_STORAGE_LOW = "SYSTEM_STORAGE_LOW"
const val ALERT_ID_SYSTEM_STORAGE_CRITICAL = "SYSTEM_STORAGE_CRITICAL"
const val ALERT_ID_BATTERY_STEEP_DISCHARGE = "BATTERY_HEALTH"
const val ALERT_ID_XIAOMI_SYSTEM_MISSING = "XIAOMI_SYSTEM_MISSING"

// Alert Titles (R747 Standardized)
const val ALERT_TITLE_LOCAL_INTERNET = "This device: Internet Lost"
const val ALERT_TITLE_RELAY_OFFLINE = "This device: Relay Lost"
const val ALERT_TITLE_TRACKER_OFFLINE = "Offline"
const val ALERT_TITLE_VIEWER_OFFLINE = "Viewer: Offline"
const val ALERT_TITLE_SIGNAL_LOSS = "Signal Lost"
const val ALERT_TITLE_VIEWER_SIGNAL_LOSS = "Viewer: Signal Lost"
const val ALERT_TITLE_JUMP_ALERT = "Jammer Alert"
const val ALERT_TITLE_VISUAL_JUMP = "Visual Jump"
const val ALERT_TITLE_TRACKER_GEOFENCE = "Geofence"
const val ALERT_TITLE_GPS_STALL = "GPS Stalled"
const val ALERT_TITLE_TRACKER_GAP = "GPS Gap"
const val ALERT_TITLE_VIEWER_GAP = "Viewer: GPS Gap"
const val ALERT_TITLE_TRACKER_POWER = "Charger unplugged"
const val ALERT_TITLE_TRACKER_BATTERY = "Low Battery"
const val ALERT_TITLE_TRACKER_TEMP = "High Temp"
const val ALERT_TITLE_TRACKER_TAMPER = "Tamper Detected"
const val ALERT_TITLE_TRACKER_TILT = "Tilt Alert"
const val ALERT_TITLE_TRACKER_ACOUSTIC = "Acoustic Alert"
const val ALERT_TITLE_TRACKER_LIFT = "Lift"
const val ALERT_TITLE_TRACKER_CHAIR = "Chair Occupied"
const val ALERT_TITLE_SYSTEM_STORAGE_LOW = "System Storage Low"
const val ALERT_TITLE_SYSTEM_STORAGE_CRITICAL = "System Storage Critical"
const val ALERT_TITLE_BATTERY_STEEP_DISCHARGE = "Critical Battery Health"
const val ALERT_TITLE_XIAOMI_SYSTEM_MISSING = "Xiaomi System Not Ready"

// System Watchdog & Grace Periods
const val ALERT_TRIGGER_GRACE_PERIOD_MS = 2000L
const val SYSTEM_WATCHDOG_INTERVAL_MS = 90000L
const val SYSTEM_WATCHDOG_THROTTLE_MS = 60000L
const val WATCHDOG_DANGER_WINDOW_MS = 20000L
const val COMMUNICATION_ALARM_GRACE_PERIOD_MS = 60000L
const val LOCATION_ALARM_GRACE_PERIOD_MS = 30000L
const val POWER_DISCONNECT_DEBOUNCE_MS = 3000L
const val SIREN_AUTO_STOP_MS = 30000L
const val SIREN_RESUME_COOLDOWN_MS = 15000L
const val ALARM_OVERLAY_THROTTLE_MS = 30000L
const val HEARTBEAT_INTERVAL_MS = 3600000L

// UI Health & Visibility
const val WATCH_DOG_UI_GRACE_MS = 15000L // Issue #427/428: Relaxed to 15s
const val SENSOR_GRACE_PERIOD_MS = 600000L
const val TEST_ALARM_DURATION_MS = 3000L

// R729: Behavioral Debouncing & Muzzle Hardening (Issue #191)
const val PROXIMITY_DEBOUNCE_STATIONARY_A15_MS = 5000L
const val PROXIMITY_DEBOUNCE_STATIONARY_MS = 3000L
const val PROXIMITY_DEBOUNCE_MOVING_MS = 1000L

// Issue #012: Adaptive Proximity Debounce
const val PROXIMITY_DEBOUNCE_MAX_MS = 15000L
const val PROXIMITY_STATIONARY_SCALING_MS_PER_HOUR = 2000L
const val PROXIMITY_STRESS_SCALING_MULTIPLIER = 2.0

// History & Persistence Logic
const val REAL_TIME_GAP_LIMIT_MS = 10000L
const val DRIFT_TOLERANCE_MS = 5000L
const val HISTORY_BUFFER_MAX_SIZE = 100
const val HISTORY_BATCH_WRITE_INTERVAL_MS = 5000L
const val DAILY_CLEANUP_HOUR = 2
const val DAILY_CLEANUP_MINUTE = 5
const val DAILY_ARCHIVE_HOUR = 3
const val DAILY_ARCHIVE_MINUTE = 30
const val DB_PRUNE_THRESHOLD = 50

// UI Performance
const val MARKER_POOL_PRUNE_THRESHOLD = 50
