package com.gps19.core.engine

/**
 * EngineConstants: Logic-specific thresholds for the tracking engine.
 * Aug.11.00:
 * - Issue #137: UI Davey/ANR Remediation. Resolved 3000ms stall by implementing 
 *   Deferred UI Hydration (R137) in SettingsComponents.kt.
 * Aug.10.32:
 * - Issue #137: Performance: Identified ANR on Settings Overlay entry.
 * Aug.10.29:
 * - Issue #134: Forensic Pulse Frequency Hardening. Added FORENSIC_PULSE_INTERVAL_MS 
 *   for high-frequency anomaly detection (R134).
 */

const val EARTH_RADIUS_METERS = 6371000.0
const val LAT_DEG_TO_METERS = 111194.92664455874
const val GRAVITY_EARTH = 9.80665

// Global App Defaults (Inherited by Engine)
const val DEFAULT_LAT = 32.7940
const val DEFAULT_LNG = 34.9896

// Performance & Latency Thresholds (Issue #589, #600)
const val LATENCY_THRESHOLD_GPS_PROCESS_MS = 100L
const val LATENCY_THRESHOLD_SENSOR_PROCESS_MS = 50L
const val LATENCY_THRESHOLD_ALARM_LOGIC_MS = 100L
const val LATENCY_THRESHOLD_DB_WRITE_MS = 1000L
const val LATENCY_THRESHOLD_JNI_MS = 100L
const val LOG_LATENCY_THRESHOLD_MS = 1000L
const val LOG_RETRIEVAL_THRESHOLD_MS = 500L
const val LOG_LIMIT_STANDARD = 1000
const val LOG_LIMIT_STRICT = 5000

// Issue #133: Silent Failure Correlation Thresholds
const val SILENT_FAILURE_CPU_THRESHOLD = 0.85
const val SILENT_FAILURE_IOW_THRESHOLD = 0.40
const val SILENT_FAILURE_LATENCY_THRESHOLD_MS = 800L

// Issue #660: Forensic Audit: Log Buffer Pressure
const val LOG_BATCH_SIZE = 50
const val LOG_BATCH_DELAY_MS = 2000L
const val LOG_BUFFER_CAPACITY = 500

// Issue #669: Forensic Spill-Buffer (MappedByteBuffer)
const val FORENSIC_SPILL_FILE_NAME = "forensic_spill.bin"
const val FORENSIC_SPILL_ENTRY_SIZE = 96 
const val FORENSIC_SPILL_CAPACITY = 3000   
const val FORENSIC_DRAIN_INTERVAL_MS = 5000L
const val FORENSIC_DRAIN_THROTTLE_MIN_MS = 500L
const val FORENSIC_DRAIN_THROTTLE_MAX_MS = 5000L

// Issue #727: Dynamic Batching
const val FORENSIC_BATCH_SIZE_MIN = 50
const val FORENSIC_BATCH_SIZE_MAX = 500
const val FORENSIC_BATCH_SIZE_DEFAULT = 100

// Issue #715: Forensic Persistence Health Alerting
const val FORENSIC_RELIABILITY_THRESHOLD = 0.85
const val FORENSIC_RELIABILITY_DEGRADATION_DURATION_MS = 30000L

// Issue #728: Storage-Aware Adaptive Pruning
const val PRUNE_CHUNK_SIZE = 100
const val ADAPTIVE_PRUNE_THRESHOLD_CRITICAL = 300
const val ADAPTIVE_PRUNE_THRESHOLD_LOW = 600
const val ADAPTIVE_PRUNE_THRESHOLD_NORMAL = 1500
const val ADAPTIVE_PRUNE_THRESHOLD_CHARGING = 3000

// Issue #700: Forensic Sampling Scaling
const val FORENSIC_SAMPLING_INTERVAL_MIN_MS = 10L  // 100Hz (Peak Fidelity)
const val FORENSIC_SAMPLING_INTERVAL_MAX_MS = 100L // 10Hz (Power Aware)
const val FORENSIC_SAMPLING_INTERVAL_COOLING_MS = 500L // Issue #709: Thermal Safety Floor

// Issue #701: Forensic Spatial Quantization
const val FORENSIC_SPATIAL_GATE_METERS = 0.1
const val FORENSIC_IMU_VIBRATION_THRESHOLD = 0.05
const val FORENSIC_IMU_TILT_THRESHOLD = 1.0

// Native Bridge Constants
const val JNI_RET_EINTR = -4
const val JNI_RET_NOT_INITIALIZED = -5

// Physics & Motion Limits
const val MAX_PHYSICAL_SPEED_MPS = 33.33 // 120 km/h
const val OUTLIER_SPEED_CAP_MPS = 83.33 // 300 km/h
const val JUMP_POINT_DISTANCE_THRESHOLD = 100.0 
const val OUTLIER_DISTANCE_THRESHOLD = 2000.0 
const val ABSOLUTE_DISTANCE_CAP_METERS = 50000.0
const val MAX_TRACTOR_ACCEL = 2.0 
const val PARKING_ACCEL_LIMIT = 1.0
const val ALTITUDE_VELOCITY_CAP = 10.0 
const val VERTICAL_VELOCITY_MAX_MPS = 5.0
const val PATH_EFFICIENCY_THRESHOLD = 0.1 
const val COMPASS_STABILITY_THRESHOLD = 20.0 
const val WILD_JUMP_THRESHOLD_METERS = 500000.0
const val MONOTONIC_JITTER_TOLERANCE_MS = 2000L

// Jump Engine Weights & Gates
const val JUMP_WEIGHT_SENSOR_MISMATCH = 60
const val JUMP_WEIGHT_ACCEL_CHECK = 40
const val JUMP_WEIGHT_ALTITUDE_DELTA = 30
const val JUMP_WEIGHT_TRADITIONAL_SPEED = 50
const val JUMP_WEIGHT_ACCURACY_LOW = 30
const val JUMP_WEIGHT_ACCURACY_HIGH = 20

const val JUMP_GATE_SENSOR_MISMATCH_MPS = 2.0
const val JUMP_GATE_SPEED_ACCURACY_LOW_MPS = 22.2
const val JUMP_GATE_SPEED_ACCURACY_HIGH_MPS = 8.3
const val JUMP_GATE_ACCURACY_LOW_THRESHOLD = 40.0
const val JUMP_GATE_ACCURACY_HIGH_THRESHOLD = 150.0
const val JUMP_GATE_VISUAL_JITTER_METERS = 10.0

// Bayesian Uncertainty Growth (R460 / Issue #460)
const val PENDING_UNCERTAINTY_GROWTH_RATE_MPS = 15.0 // 54 km/h conservative drift
const val PENDING_UNCERTAINTY_DRIFT_STATIONARY_MPS = 1.5 // Minimal drift when stationary
const val PENDING_UNCERTAINTY_SPEED_CAP_MPS = 33.3 // 120 km/h cap

// Position EMA Parameters (Issue #504 Replacement for IMM)
const val POSITION_EMA_ALPHA_DEFAULT = 0.3
const val POSITION_EMA_ALPHA_STATIONARY = 0.1
const val POSITION_EMA_ALPHA_SUSPICIOUS = 0.05
const val SPEED_EMA_ALPHA = 0.2
const val BEARING_EMA_ALPHA = 0.1
const val STATIONARY_SPEED_THRESHOLD_MPS = 0.5
const val POSITION_STALL_RECOVERY_DT_SEC = 60.0

// Behavioral Sentinel Checks
const val JUMP_CHECK_MIN_DIST = 5.0
const val ACCEL_CHECK_MIN_DIST = 10.0
const val EFFICIENCY_MIN_SEGMENT_DIST = 10.0
const val EFFICIENCY_MIN_TOTAL_DIST = 50.0
const val SCATTER_MIN_SPEED_MPS = 0.5
const val SCATTER_ANGLE_THRESHOLD = 120.0

// Acoustic Monitoring (R810-L)
const val BREACH_THRESHOLD_DB_JUMP = 40.0 
const val ACOUSTIC_THRESHOLD_DB_JUMP = 40.0 
const val ACOUSTIC_SUSPICIOUS_THRESHOLD_DB_JUMP = 20.0
const val ACOUSTIC_MIN_THRESHOLD_DB = 50.0
const val ACOUSTIC_FLOOR_MIN_DB = 50.0 
const val ACOUSTIC_FLOOR_CONTRACTION_EMA = 0.995
const val ACOUSTIC_LOCKOUT_MS = 1000L
const val ACOUSTIC_RECOVERY_DELAY_MS = 30000L
const val ACOUSTIC_SAMPLE_RATE = 8000
const val ACOUSTIC_INIT_RETRY_COUNT = 3
const val ACOUSTIC_INIT_RETRY_DELAY_MS = 200L
const val ACOUSTIC_GENERIC_RECOVERY_DELAY_MS = 2000L

// Issue #526: Acoustic Duty Cycle
const val ACOUSTIC_DUTY_CYCLE_ON_MS = 2000L
const val ACOUSTIC_DUTY_CYCLE_OFF_MS = 8000L

// Physical Security Sentinel (R810-M)
const val LIGHT_THRESHOLD_LUX_JUMP = 150.0
const val TILT_THRESHOLD_DEGREES = 15.0
const val BARO_LIFT_THRESHOLD_METERS = 0.8
const val VIBRATION_SUSPICIOUS_THRESHOLD_G = 0.25
const val VIBRATION_SHOCK_THRESHOLD_G = 0.8 
const val VIBRATION_STATIONARY_THRESHOLD = 0.12 
const val STATIONARY_FLOOR_MULT = 1.5
const val VIBRATION_SHOCK_MULTIPLIER = 7.0
const val VIBRATION_SUSPICIOUS_MULTIPLIER = 2.5
const val INITIAL_VIBRATION_FLOOR = 0.05
const val VIBRATION_WINDOW_SIZE = 5 
const val PASSIVE_ZEROING_STATIONARY_MS = 300000L
const val ROTATION_INIT_STATIONARY_MS = 3000L
const val BARO_ZEROING_INTERVAL_MS = 300000L 
const val SPIKE_DEBOUNCE_MS = 5000L

// Issue #601: Kinetic Energy Anomaly Detection
const val VIBRATION_HPF_ALPHA = 0.9 // DC-removal for Kinetic Energy
const val VIBRATION_ENERGY_EMA_ALPHA = 0.1 // Kinetic Energy smoothing

// Sitting Detection: Chair Plunge (R999b)
const val CHAIR_PLUNGE_PHASE_TIMEOUT_MS = 5000L
const val CHAIR_PLUNGE_WINDOW_MS = 1000L
const val CHAIR_PLUNGE_VELOCITY_THRESHOLD = 0.25
const val CHAIR_PLUNGE_DISTANCE_THRESHOLD = 0.15
const val SIT_DUPLICATE_GUARD_MS = 10000L
const val MUZZLE_HYSTERESIS_MS = 2000L

// Filtering Thresholds (R810-P Zero-Lag)
const val SUSPICIOUS_Q_SCALE = 1000.0
const val HIGH_ACCURACY_THRESHOLD_METERS = 35.0
const val TRAJECTORY_REJECTION_ACCURACY_MULT = 3.0

const val ACCURACY_WINDOW_BUCKET_MS = 120000L
const val ACCURACY_WINDOW_MAX_SIZE = 4
const val GEOFENCE_ACCURACY_HYSTERESIS_MULT = 1.10
const val GEOFENCE_ACCURACY_EXPANSION_MULT = 1.0
const val GEOFENCE_BUFFER_MULT = 6.0
const val GEOFENCE_HYSTERESIS_METERS = 5.0
const val GEOFENCE_PREDICTIVE_LOOKAHEAD_S = 2.0
const val GEOFENCE_PREDICTIVE_MIN_SPEED_MPS = 1.0

// EMA Factors (Issue #263: Corrected Inversion)
const val LUX_EMA_SLOW = 0.01
const val LUX_EMA_FAST = 0.1
const val LUX_EMA_UP_SLOW = 0.001
const val LUX_EMA_UP_FAST = 0.01
const val LUX_EMA_DOWN_SLOW = 0.001
const val LUX_EMA_DOWN_FAST = 0.02
const val ACOUSTIC_EMA_DOWN_SLOW = 0.001
const val ACOUSTIC_EMA_DOWN_FAST = 0.02
const val ACOUSTIC_EMA_UP_SLOW = 0.0001
const val ACOUSTIC_EMA_UP_FAST = 0.01
const val VIBRATION_EMA_DOWN_SLOW = 0.01
const val VIBRATION_EMA_DOWN_FAST = 0.1
const val VIBRATION_EMA_UP_SLOW = 0.001
const val VIBRATION_EMA_UP_FAST = 0.01
const val BARO_EMA_SLOW = 0.001 
const val PROXIMITY_EMA_ALPHA = 0.15

// Engine Execution Parameters
const val BOOTSTRAP_PHASE_MS = 60000L
const val DISCOVERY_PHASE_MS = 60000L
const val JUMP_HOLD_DURATION_MS = 180000L
const val MOVING_HOLD_DURATION_MS = 60000L
const val GPS_GAP_THRESHOLD_MS = 60000L
const val GPS_STALL_THRESHOLD_MS = 60000L
const val JAMMER_DETECTION_THRESHOLD_MS = 180000L
const val LOCATION_RECOVERY_DEBOUNCE_MS = 3000L

// Adaptive Polling Strategy (R406a)
const val TICK_INTERVAL_MS = 2000L
const val POWER_SAVE_TICK_INTERVAL_MS = 10000L
const val UI_PULSE_TIMEOUT_MS = 45000L 
const val FGS_STICKY_DELAY_MS = 45000L
const val WATCH_TIMEOUT_MS = 15000L 
const val CLOCK_REGRESSION_GATE_MS = 100L
const val SENSOR_WARMING_MS = 5000L
const val SUSPICIOUS_STATE_COOLDOWN_MS = 60000L
const val ADAPTATION_SETTLING_MS = 5000L 
const val GPS_REVIVAL_RETRY_INTERVAL_MS = 120000L
const val MAX_REVIVAL_ATTEMPTS = 3
const val HARDWARE_BOOT_GRACE_MS = 30000L
const val LANDING_PAGE_PAUSE_MS = 2000L
const val STARTUP_SETTLING_DELAY_MS = 3000L

// GPS Polling Intervals (Central Authority)
const val HIGH_FREQUENCY_GPS_POLLING_MS = 2000L
const val MOVING_GPS_POLLING_MS = 5000L
const val STATIONARY_GPS_POLLING_MS = 60000L
const val SCREEN_OFF_GPS_POLLING_MS = 45000L
const val SUSPICIOUS_GPS_POLLING_MS = 10000L
const val COOLING_GPS_POLLING_MS = 30000L
const val VIEWER_GPS_POLLING_MS = 10000L

// Hardware Heuristic Recovery (Issue #502)
const val HARDWARE_SUPPRESSION_THRESHOLD_MS = 15000L
const val HARDWARE_RECOVERY_COOLDOWN_MS = 60000L

const val ACTIVE_MOVE_THRESHOLD = 2.0
const val GPS_SAVE_INTERVAL_MS = 20000L 

// Stationary Anchor Monitor (Issue #062 - R990)
const val PARKING_ANCHOR_MIN_DIST = 6.0
const val PARKING_ANCHOR_FACTOR = 0.8
const val ANCHOR_ENGAGEMENT_PROBABILITY = 0.9
const val ANCHOR_ESCAPE_SCORE_THRESHOLD = 100.0
const val ANCHOR_TREND_WINDOW_SIZE = 3
const val ANCHOR_AVERAGING_WINDOW_SIZE = 8
const val ANCHOR_TRANSITION_ZONE_START = 0.5 
const val ANCHOR_VELOCITY_WEIGHT_MPS = 15.0 
const val ANCHOR_DISPLACEMENT_WEIGHT = 8.0 
const val ANCHOR_IMU_DAMPING_FACTOR = 0.5 
const val ANCHOR_ACCURACY_PENALTY_LIMIT = 40.0 

const val DEDUPLICATION_SPATIAL_GATE_FACTOR = 0.5 

// Behavioral State Thresholds (Issue #302)
const val SUSTAINED_SPEED_THRESHOLD = 2 
const val SUSTAINED_SPEED_STATIONARY_THRESHOLD = 4
const val STATE_CONFIDENCE_BUFFER_MS = 2000L
const val PARKING_CONFIDENCE_BUFFER_MS = 5000L
const val HIGH_SPEED_PROMOTION_THRESHOLD = 5.0

// Throttling Limits
const val THROTTLE_LUX_LIMIT = 50.0
const val THROTTLE_TILT_LIMIT = 5.0
const val THROTTLE_ACOUSTIC_LIMIT = 15.0
const val THROTTLE_COMPASS_LIMIT = 5.0
const val THROTTLE_BARO_LIMIT = 0.5
const val GNSS_SAMPLING_INTERVAL_MS = 2000L

// System Thresholds (Core Logic)
const val TRACKER_SIGNAL_LOSS_THRESHOLD_MS = 180000L
const val VIEWER_SIGNAL_LOSS_THRESHOLD_MS = 30000L
const val INTERNET_LOSS_THRESHOLD_MS = 60000L 
const val DISTANCE_ALARM_SAMPLES_REQUIRED = 6
const val DEFAULT_ACCURACY_FALLBACK = 15.0
const val RETURN_TO_SAFE_RANGE_ACCURACY_LIMIT = 20.0

// Battery thresholds (R716e)
const val BATTERY_ALARM_THRESHOLD = 20
const val CRITICAL_BATTERY_THRESHOLD = 20
const val MAX_SAFE_TEMPERATURE_CELSIUS = 46.0
const val MAX_SAFE_TEMPERATURE_RECOVERY = 44.0
const val BATTERY_STEEP_DISCHARGE_THRESHOLD = 5
const val BATTERY_STEEP_DISCHARGE_WINDOW_MS = 600000L

// Storage thresholds
const val SYSTEM_STORAGE_CRITICAL_THRESHOLD_MB = 10L
const val SYSTEM_STORAGE_LOW_THRESHOLD_MB = 50L
const val SYSTEM_STORAGE_CRITICAL_THRESHOLD_PCT = 0.01 // 1%
const val SYSTEM_STORAGE_LOW_THRESHOLD_PCT = 0.05 // 5%

// GPS Polling & Filtering (v8.7.5 Centralization)
const val GPS_SEQUENCE_TOLERANCE_MS = 60000L
const val GPS_MIN_UPDATE_DISTANCE_METERS = 2.0

// Analytical Index Thresholds
const val GPS_INDEX_AGE_EXCELLENT_SEC = 5.0
const val GPS_INDEX_AGE_SCALING = 2.0
const val GPS_INDEX_ACCURACY_EXCELLENT_METERS = 8.0
const val GPS_INDEX_SATS_TARGET = 12

// Forensic Ribbon Scaling
const val RIBBON_NOISE_SCALE_DB = 40.0
const val RIBBON_LUX_LOG_SCALE = 5.0
const val RIBBON_VIBRATION_SCALE_G = 2.0
const val RIBBON_KINETIC_ENERGY_SCALE = 2.0
const val RIBBON_LIFT_SCALE_METERS = 5.0
const val RIBBON_SNR_SCALE_DB = 45.0
const val RIBBON_CURRENT_SCALE_MA = 1000.0
const val RIBBON_SIT_TILT_SCALE_DEG = 15.0
const val RIBBON_SIT_BARO_SCALE_METERS = 2.0
const val RIBBON_CPU_LOAD_SCALE = 1.0
const val RIBBON_IO_WAIT_SCALE = 1.0
const val RIBBON_LATENCY_SCALE_MS = 1000.0

const val SENSOR_SAMPLE_BUFFER_MAX_AGE_MS = 300000L
const val MAX_BACKFILL_POINTS = 1000

// Network Communication (v8.8.21)
const val SIGNALING_EMIT_DELAY_MS = 50L
const val MAX_ALLOWED_RTT_MS = 5000
const val COMM_RTT_FLOOR_MS = 150
const val COMM_RTT_SCALING_FACTOR = 2000.0
const val NETWORK_TIMEOUT_MS = 60000
const val NET_REJOIN_THRESHOLD_MS = 15000L
const val NET_HEAL_THRESHOLD_MS = 45000L
const val PING_INTERVAL_MS = 10000L
const val SOCKET_TIMEOUT_MS = 60000
const val RTT_WINDOW_SIZE = 5

// Trajectory & Persistence (v8.8.35)
const val HOME_POINT_REFRESH_INTERVAL_MS = 30000L

// Logging & UI (v8.9.2)
const val MAX_HISTORY_POINTS_PER_RIBBONS = 240
const val GPS_STABILITY_AUDIT_INTERVAL_MS = 10000L
const val GPS_STABILITY_GAP_THRESHOLD_MS = 200L
const val GPS_STABILITY_RELIABILITY_THRESHOLD = 98.0
const val GNSS_EXPECTED_INTERVAL_MS = 1000L
const val GNSS_JITTER_THRESHOLD_MS = 500L

// Unified UI Staleness Threshold
const val TELEMETRY_UI_STALE_THRESHOLD_MS = 35000L
const val GPS_UI_FAIL_THRESHOLD_MS = 35000L

// R993: Notification Throttling
const val NOTIFICATION_THROTTLE_MS = 30000L

// Alert Internal IDs (Aligned with SoT)
const val ALERT_ID_LOCAL_INTERNET = "LOCAL_INTERNET"
const val ALERT_ID_RELAY_OFFLINE = "RELAY_OFFLINE"
const val ALERT_ID_TRACKER_OFFLINE = "TRACKER_OFFLINE"
const val ALERT_ID_SIGNAL_LOSS = "SIGNAL_LOSS"
const val ALERT_ID_JUMP_ALERT = "JUMP_ALERT"
const val ALERT_ID_VISUAL_JUMP = "VISUAL_JUMP"
const val ALERT_ID_TRACKER_GEOFENCE = "GEOFENCE_VIOLATION"
const val ALERT_ID_GPS_STALL = "GPS_STALL"
const val ALERT_ID_TRACKER_GAP = "GPS_GAP"
const val ALERT_ID_TRACKER_POWER = "POWER_TAMPER"
const val ALERT_ID_TRACKER_BATTERY = "LOW_BATTERY"
const val ALERT_ID_TRACKER_TEMP = "TRACKER_TEMP"
const val ALERT_ID_TRACKER_TAMPER = "TRACKER_TAMPER"
const val ALERT_ID_TRACKER_TILT = "TILT_ALERT"
const val ALERT_ID_TRACKER_ACOUSTIC = "ACOUSTIC_ALERT"
const val ALERT_ID_TRACKER_LIFT = "LIFT_ALERT"
const val ALERT_ID_TRACKER_CHAIR = "CHAIR_SIT"
const val ALERT_ID_SYSTEM_STORAGE_LOW = "SYSTEM_STORAGE_LOW"
const val ALERT_ID_SYSTEM_STORAGE_CRITICAL = "SYSTEM_STORAGE_CRITICAL"
const val ALERT_ID_BATTERY_STEEP_DISCHARGE = "BATTERY_HEALTH"
const val ALERT_ID_HARDWARE_CONFIGURATION = "HARDWARE_CONFIG_MISSING"
const val ALERT_ID_PERFORMANCE_SPIKE = "PERFORMANCE_SPIKE"
const val ALERT_ID_FORENSIC_OVERFLOW = "FORENSIC_OVERFLOW"
const val ALERT_ID_GPS_HARDWARE_LOCK = "GPS_HARDWARE_LOCK"
const val ALERT_ID_SILENT_FAILURE = "SILENT_FAILURE"

// Alert Titles (R747 Standardized)
const val ALERT_TITLE_LOCAL_INTERNET = "This device: Internet Lost"
const val ALERT_TITLE_RELAY_OFFLINE = "This device: Relay Lost"
const val ALERT_TITLE_TRACKER_OFFLINE = "Offline"
const val ALERT_TITLE_VIEWER_OFFLINE = "Viewer: Offline"
const val ALERT_TITLE_SIGNAL_LOSS = "Signal Lost"
const val ALERT_TITLE_VIEWER_SIGNAL_LOSS = "Viewer: Signal Lost"
const val ALERT_TITLE_JUMP_ALERT = "Jammer Alert"
const val ALERT_TITLE_VISUAL_JUMP = "Visual Jump"
const val ALERT_TITLE_TRACKER_GEOFENCE = "Geofence"
const val ALERT_TITLE_GPS_STALL = "GPS Stalled"
const val ALERT_TITLE_TRACKER_GAP = "GPS Gap"
const val ALERT_TITLE_VIEWER_GAP = "Viewer: GPS Gap"
const val ALERT_TITLE_TRACKER_POWER = "Charger unplugged"
const val ALERT_TITLE_TRACKER_BATTERY = "Low Battery"
const val ALERT_TITLE_TRACKER_TEMP = "High Temp"
const val ALERT_TITLE_TRACKER_TAMPER = "Tamper Detected"
const val ALERT_TITLE_TRACKER_TILT = "Tilt Alert"
const val ALERT_TITLE_TRACKER_ACOUSTIC = "Acoustic Alert"
const val ALERT_TITLE_TRACKER_LIFT = "Lift"
const val ALERT_TITLE_SYSTEM_STORAGE_LOW = "This device: Storage Low"
const val ALERT_TITLE_SYSTEM_STORAGE_CRITICAL = "This device: Storage Critical"
const val ALERT_TITLE_BATTERY_STEEP_DISCHARGE = "This device: Battery Health"
const val ALERT_TITLE_HARDWARE_CONFIGURATION = "This device: Hardware Config"
const val ALERT_TITLE_PERFORMANCE_SPIKE = "This device: Performance Warning"
const val ALERT_TITLE_FORENSIC_OVERFLOW = "This device: Forensic Buffer Overflow"
const val ALERT_TITLE_GPS_HARDWARE_LOCK = "This device: GPS Hardware Lock"
const val ALERT_TITLE_SILENT_FAILURE = "Forensic: Silent Failure"

// System Watchdog & Grace Periods
const val ALERT_TRIGGER_GRACE_PERIOD_MS = 2000L
const val SYSTEM_WATCHDOG_INTERVAL_MS = 90000L
const val SYSTEM_WATCHDOG_THROTTLE_MS = 60000L
const val WATCHDOG_DANGER_WINDOW_MS = 20000L
const val COMMUNICATION_ALARM_GRACE_PERIOD_MS = 60000L
const val LOCATION_ALARM_GRACE_PERIOD_MS = 30000L
const val POWER_DISCONNECT_DEBOUNCE_MS = 3000L
const val SIREN_AUTO_STOP_MS = 30000L
const val SIREN_RESUME_COOLDOWN_MS = 15000L
const val ALARM_OVERLAY_THROTTLE_MS = 30000L
const val HEARTBEAT_INTERVAL_MS = 360000L
const val INTEGRITY_HEARTBEAT_INTERVAL_MS = 60000L
const val FORENSIC_PULSE_INTERVAL_MS = 10000L

// UI Health & Visibility
const val WATCH_DOG_UI_GRACE_MS = 15000L 
const val SENSOR_GRACE_PERIOD_MS = 600000L
const val TEST_ALARM_DURATION_MS = 3000L

// R729: Behavioral Debouncing
const val PROXIMITY_DEBOUNCE_STATIONARY_MS = 5000L
const val PROXIMITY_DEBOUNCE_MOVING_MS = 1000L

// Issue #012: Adaptive Proximity Debounce
const val PROXIMITY_DEBOUNCE_MAX_MS = 15000L
const val PROXIMITY_STATIONARY_SCALING_MS_PER_HOUR = 2000L
const val PROXIMITY_STRESS_SCALING_MULTIPLIER = 2.0

// History & Persistence Logic
const val REAL_TIME_GAP_LIMIT_MS = 10000L
const val DRIFT_TOLERANCE_MS = 5000L
const val HISTORY_BUFFER_MAX_SIZE = 100
const val HISTORY_BATCH_WRITE_INTERVAL_MS = 5000L
const val DAILY_CLEANUP_HOUR = 2
const val DAILY_CLEANUP_MINUTE = 5
const val DAILY_ARCHIVE_HOUR = 3
const val DAILY_ARCHIVE_MINUTE = 30
const val DB_PRUNE_THRESHOLD = 50

// UI Performance
const val MARKER_POOL_PRUNE_THRESHOLD = 50
const val LOG_MUZZLE_STARTUP_MS = 60000L

const val FORENSIC_PINK_COLOR = 0xFFFF00FF.toInt()

// Maintenance Recovery (Issue #108)
const val MAINTENANCE_WORK_NAME = "GPS_Maintenance"
const val RECOVERY_THRESHOLD_MS = 180000L
const val RECOVERY_GRACE_PERIOD_MS = 60000L

// Audio Synthesizer Parameters
const val SIREN_SAMPLE_RATE = 44100
const val SIREN_FADE_IN_DURATION_MS = 1000L
