package com.gps19.core.engine

import kotlinx.serialization.Serializable

@Serializable
data class LocationUpdate(
    val lat: Double = 0.0, val lng: Double = 0.0, val alt: Double = 0.0,
    val speed: Float = 0f, val accuracy: Float = 0f, val bearing: Float = 0f,
    val battery: Int = -1, val temp: Float = 0f, val maxTemp: Float = 0f,
    val isCharging: Boolean = false, val gpsTs: Long = 0L, val isMe: Boolean = true,
    val ts: Long = 0L,
    val isJump: Boolean = false, val isTrajectoryPromoted: Boolean = false,
    val jumpTier: Int = 0,
    val isJammer: Boolean = false, val isStalled: Boolean = false,
    val distToTracker: Double? = null, val distToHome: Double? = null,
    val totalConnectedMs: Long? = null, val sessionConnectedMs: Long? = null,
    val lastConnTs: Long? = null, val lastDiscTs: Long? = null,
    val satsView: Int = 0, val satsUsed: Int = 0, val maxAccuracy: Float = 0f,
    val uptimeMs: Long? = null, val totalDropMs: Long? = null, val maxDropMs: Long? = null, val maxDropTs: Long? = null,
    val vibration: Float? = null, val heading: Float? = null, val baroAlt: Float? = null,
    val icon: String? = null, 
    val lux: Float? = null, val isNear: Boolean? = null, val tiltDegrees: Float? = null,
    val acousticDb: Double? = null,
    val luxBaseline: Float? = null,
    val acousticFloorDb: Double? = null,
    val peakVibrationShock: Float? = null,
    val peakVibrationShockTs: Long? = null,
    val adaptiveVibrationFloor: Float? = null,
    val isSuspicious: Boolean = false,
    val isTamperDetected: Boolean = false,
    val proxIdx: Float? = null,
    val proximityCm: Float? = null,
    val currentMa: Int = 0,
    val signal: Int? = null,
    val micPending: Boolean = false,
    val isPowerTamper: Boolean = false,
    val violationUptimeMs: Long? = null,
    val violationPercentage: Float? = null,
    val isSitDetected: Boolean = false,
    val isSitActive: Boolean = false,
    val lastSitTs: Long = 0L,
    val verticalVelocity: Float? = null,
    val sitVz: Float? = null,
    val sitDz: Float? = null,
    val sitBaro: Float? = null,
    val sitTilt: Float? = null,
    val sitShock: Float? = null,
    val isClockRegression: Boolean = false,
    val isLocationPending: Boolean = false,
    val isPowerSaveMode: Boolean = false,
    val standbyBucket: Int = -1,
    val netInterface: String = "UNKNOWN",
    val isStorageLow: Boolean = false,
    val isStorageCritical: Boolean = false,
    val gnssDetail: GnssDetail? = null,
    val snrIdx: Float = 0f,
    val isBatterySteepDischarge: Boolean = false,
    val isCoolingModeActive: Boolean = false
)
