package com.gps19.app

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner

/**
 * HiltTestRunner: Custom test runner to enable Hilt in instrumentation tests.
 * Uses GpsTestApplication_Application (generated by @CustomTestApplication) 
 * to ensure WorkManager is initialized via GpsTestBaseApplication.
 * Note: Using string-based instantiation to bypass bootstrap compilation circularity.
 */
class HiltTestRunner : AndroidJUnitRunner() {
    override fun newApplication(cl: ClassLoader, className: String, context: Context): Application {
        return super.newApplication(cl, "com.gps19.app.GpsTestApplication_Application", context)
    }
}
